# Use the latest httpd image (latest numerical tag)
FROM httpd:2.4

# Copy your HTML file to the httpd default directory
COPY index.html /usr/local/apache2/htdocs/index.html

# Expose port 8086
EXPOSE 8086
