# Use the latest nginx image
FROM nginx:latest

# Copy your HTML file to the nginx default directory
COPY index.html /usr/share/nginx/html/index.html

# Expose ports 8085 and 3000
EXPOSE 8085
EXPOSE 3000
